### ISSUE TITLE
v0.14 stable version task list

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluentd#1185]
- [ ] Remove dependency of parsers only for exec plugins from exec plugins, switch to use normal parsers
- [x] Fix bug of process handling on Windows ( #1084 )
- [x] Mark `host` and `port` out of `<server>` sections as deprecated ( #1186 )
- [x] Fix bug to restart worker process for configuration errors ( #1180 #1183 )
- [ ] Remove all warnings

**Comment by repeatedly** [comment]
v1.0 has been released.
