### ISSUE TITLE
fluentd v0.14.0 TODO before official release

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluentd#987]
We have a plan to release v0.14.0 soon and it means "gem install fluentd" installs v0.14.0, not v0.12.
We should avoid troubles on production. If we have a problem, our QA process should be improved.

## Must

- [ ] Check popular exsiting plugins work or not.
- [ ] Check the performance on popular cases, tail, multiple forwarding, copy, label.
- [ ] Check Windows support.
- [ ] Check interoperability between v0.12 and v0.14.

## Optional

- [ ] Add new feature documents to docs.fluentd.org.
- [ ] v0.14.0 misc documents to docs.fluentd.org, e.g. how to develop plugins by v0.14 way.
- [ ] Migration tool for plugins and configurations.

**Comment by tagomoris** [comment]
Do you have existing lists of details of each items for v0.12 versions? If so, please add details of each items.
Or brand new one?

**Comment by repeatedly** [comment]
> Do you have existing lists of details of each items for v0.12 versions?

I have no detailed list so I will add it to Wiki.

**Comment by tagomoris** [comment]
I updated description to move an item "Add new feature documents to docs.fluentd.org" to Optional, because there's almost no new features available immediately with plugins on v0.12 APIs. Moreover, there are almost no plugins on v0.14 APIs.

The only thing is `time_as_integer`, but it's `true` in default. I think we can update documents later.

**Comment by repeatedly** [comment]
Here is the draft of TODO: https://github.com/fluent/fluentd/wiki/Release-TODO-before-release-new-major-version
I will add configurations to fluentd-benchmark for performance check.
If maintainers have a good idea for QA, please update above document directly.

**Comment by tagomoris** [comment]
The full operations should be scripted and automated... in (near) future.

**Comment by tagomoris** [comment]
Now I'm operating benchmarks at this gist:
https://gist.github.com/tagomoris/6a540589b92ba02ae88eea112663052f
